trigger:
- main

pool:
  name: 'python-pool'
  demands:
  - Agent.Name -equals LHIETBRINKWORK

variables:
  PYTHON_ROOT: 'D:\agent\_work\_tool\Python\3.12.9\x64'
  PIP_CACHE_DIR: 'D:\agent\_work\_temp\.pipcache'

steps:
- task: UsePythonVersion@0
  inputs:
    disableDownloadFromRegistry: true
    versionSpec: '3.12.9'
    addToPath: true
    architecture: 'x64'

- script: |
    echo Using Python from $(PYTHON_ROOT)
    python --version
    python -m pip install --upgrade pip
    python -m pip install wheel setuptools
  displayName: 'Update pip and install basic tools'

- script: |
    python -m pip install -r requirements.txt --cache-dir $(PIP_CACHE_DIR)
  displayName: 'Install dependencies'

- script: |
    python -m pytest tests/ --junitxml=junit/test-results.xml
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results.xml'
    mergeTestResults: true
    testRunTitle: 'Python tests'
  condition: succeededOrFailed()